apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita
  labels:
    app: sc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc
  template:
    metadata:
      labels:
        app: sc
    spec:
      dnsPolicy: Default
      containers:
        - name: sc
          image: dzulfiqar12/sejutacita:latest
          envFrom:
            - secretRef:
                name: prod-secrets
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sc
spec:
  selector:
    app: sc
  type: LoadBalancer
  ports:
    - name: defaultport
      protocol: TCP
      port: 80
      targetPort: 3000
